/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MOnw5KVjT5j
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";

export default function Component() {
  const [lists, setLists] = useState([
    {
      title: "To Do",
      cards: [
        {
          title: "Design Landing Page",
          description: "Create a modern and responsive landing page design.",
        },
        {
          title: "Implement Authentication",
          description: "Integrate email and social authentication.",
        },
        {
          title: "Build Dashboard",
          description: "Design and develop the admin dashboard.",
        },
      ],
    },
    {
      title: "In Progress",
      cards: [
        {
          title: "Integrate API",
          description: "Connect the app to the backend API.",
        },
        {
          title: "Optimize Performance",
          description: "Improve app speed and responsiveness.",
        },
      ],
    },
    {
      title: "Done",
      cards: [
        {
          title: "Set up CI/CD",
          description: "Implement continuous integration and deployment.",
        },
      ],
    },
  ]);

  const [newCardTitle, setNewCardTitle] = useState("");
  const [newCardDescription, setNewCardDescription] = useState("");
  const [addingCardIndex, setAddingCardIndex] = useState<number | null>(null);
  const [newListTitle, setNewListTitle] = useState("");
  const [addingList, setAddingList] = useState(false);

  const addCard = (listIndex: number) => {
    const newCard = { title: newCardTitle, description: newCardDescription };
    const newLists = lists.map((list, index) =>
      index === listIndex ? { ...list, cards: [...list.cards, newCard] } : list
    );
    setLists(newLists);
    setNewCardTitle("");
    setNewCardDescription("");
    setAddingCardIndex(null);
  };

  const addList = () => {
    const newList = { title: newListTitle, cards: [] };
    setLists([...lists, newList]);
    setNewListTitle("");
    setAddingList(false);
  };

  return (
    <div className="flex min-h-screen w-full bg-background">
      <main className="flex w-full flex-1 flex-col gap-8 p-6 sm:p-10 md:gap-12">
        <div className="flex items-center gap-4">
          <h1 className="text-3xl font-bold">Project Board</h1>
          <div className="ml-auto flex items-center gap-3">
            {addingList ? (
              <>
                <Input
                  placeholder="List Title"
                  value={newListTitle}
                  onChange={(e) => setNewListTitle(e.target.value)}
                />
                <Button
                  size="sm"
                  variant="outline"
                  className="rounded-md bg-muted px-4 py-2 text-sm font-medium text-muted-foreground shadow-sm transition-colors hover:bg-muted/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  onClick={addList}
                >
                  追加
                </Button>
              </>
            ) : (
              <Button
                size="sm"
                variant="outline"
                className="rounded-md bg-muted px-4 py-2 text-sm font-medium text-muted-foreground shadow-sm transition-colors hover:bg-muted/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                onClick={() => setAddingList(true)}
              >
                Add List
              </Button>
            )}
          </div>
        </div>
        <div className="grid w-full grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {lists.map((list, listIndex) => (
            <Card
              key={listIndex}
              className="flex flex-col gap-6 rounded-lg border bg-card p-6 shadow-sm"
            >
              <div className="flex items-center gap-3">
                <h2 className="text-xl font-semibold">{list.title}</h2>
                <Badge
                  variant="outline"
                  className="ml-auto rounded-full bg-muted px-3 py-1 text-xs font-medium text-muted-foreground"
                >
                  {list.cards.length}
                </Badge>
              </div>
              <ScrollArea className="flex-1">
                <div className="grid gap-4">
                  {list.cards.map((card, cardIndex) => (
                    <Card
                      key={cardIndex}
                      as="div"
                      className="cursor-pointer rounded-lg border bg-card-background p-4 shadow-sm transition-all hover:bg-accent hover:text-accent-foreground"
                    >
                      <h3 className="text-base font-medium">{card.title}</h3>
                      <p className="text-sm text-muted-foreground">
                        {card.description}
                      </p>
                    </Card>
                  ))}
                </div>
              </ScrollArea>
              {addingCardIndex === listIndex ? (
                <div className="flex flex-col gap-3">
                  <Input
                    placeholder="Card Title"
                    value={newCardTitle}
                    onChange={(e) => setNewCardTitle(e.target.value)}
                  />
                  <Textarea
                    placeholder="Card Description"
                    value={newCardDescription}
                    onChange={(e) => setNewCardDescription(e.target.value)}
                  />
                  <Button
                    size="sm"
                    variant="ghost"
                    className="w-full rounded-md bg-card-background px-4 py-2 text-sm font-medium text-muted-foreground shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                    onClick={() => addCard(listIndex)}
                  >
                    追加
                  </Button>
                </div>
              ) : (
                <Button
                  size="sm"
                  variant="ghost"
                  className="w-full rounded-md bg-card-background px-4 py-2 text-sm font-medium text-muted-foreground shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  onClick={() => setAddingCardIndex(listIndex)}
                >
                  Add Card
                </Button>
              )}
            </Card>
          ))}
        </div>
      </main>
    </div>
  );
}
